FROM ubuntu:18.04

LABEL artifactId="{{.ArtifactId}}"
LABEL groupId="{{.GroupId}}"
LABEL team-name="{{.Team.Name}}"
LABEL team-email="{{.Team.Email}}"

COPY . /app
RUN make /app
CMD python /app/app.py
