FROM openjdk:19-alpine

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

LABEL artifactId="{{.ArtifactId}}"
LABEL groupId="{{.GroupId}}"
LABEL team-name="{{.Team.Name}}"
LABEL team-email="{{.Team.Email}}"
LABEL key1="{{ index .Render "key1" }}"

ARG JAR_FILE=target/*.jar

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
